/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./components/ActionButton.vue')['default']
    BiArrowUpLeft: typeof import('~icons/bi/arrow-up-left')['default']
    BottomBar: typeof import('./components/BottomBar.vue')['default']
    CodeLine: typeof import('./components/CodeLine.vue')['default']
    CodeTag: typeof import('./components/CodeTag.vue')['default']
    Cursor: typeof import('./components/Cursor.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    MdiCalendarRangeOutline: typeof import('~icons/mdi/calendar-range-outline')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    PorjectItemCover: typeof import('./components/PorjectItemCover.vue')['default']
    PortfolioScrubber: typeof import('./components/PortfolioScrubber.vue')['default']
    ProjectCover: typeof import('./components/ProjectCover.vue')['default']
    ProjectItemCover: typeof import('./components/ProjectItemCover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollHint: typeof import('./components/ScrollHint.vue')['default']
    StatusIndicator: typeof import('./components/StatusIndicator.vue')['default']
  }
}
