/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./components/ActionButton.vue')['default']
    BiArrowUpLef: typeof import('~icons/bi/arrow-up-lef')['default']
    BiArrowUpLeft: typeof import('~icons/bi/arrow-up-left')['default']
    BiGithub: typeof import('~icons/bi/github')['default']
    BiLinkedin: typeof import('~icons/bi/linkedin')['default']
    BottomBar: typeof import('./components/BottomBar.vue')['default']
    CodeLine: typeof import('./components/CodeLine.vue')['default']
    CodeTag: typeof import('./components/CodeTag.vue')['default']
    Cursor: typeof import('./components/Cursor.vue')['default']
    Fa6SolidArrowLeftLong: typeof import('~icons/fa6-solid/arrow-left-long')['default']
    FluentArrowUpLeft24Filled: typeof import('~icons/fluent/arrow-up-left24-filled')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    LinkButton: typeof import('./components/LinkButton.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    OcticonArrowUpLeft16: typeof import('~icons/octicon/arrow-up-left16')['default']
    PhArrowUpLeftBold: typeof import('~icons/ph/arrow-up-left-bold')['default']
    PhArrowUpRightBold: typeof import('~icons/ph/arrow-up-right-bold')['default']
    PorjectItemCover: typeof import('./components/PorjectItemCover.vue')['default']
    PortfolioScrubber: typeof import('./components/PortfolioScrubber.vue')['default']
    Preloader: typeof import('./components/Preloader.vue')['default']
    ProjectCover: typeof import('./components/ProjectCover.vue')['default']
    ProjectItemCover: typeof import('./components/ProjectItemCover.vue')['default']
    RiTwitterXLine: typeof import('~icons/ri/twitter-x-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollHint: typeof import('./components/ScrollHint.vue')['default']
    SolarDoubleAltArrowLeftBold: typeof import('~icons/solar/double-alt-arrow-left-bold')['default']
    SolarDoubleAltArrowLeftBroken: typeof import('~icons/solar/double-alt-arrow-left-broken')['default']
    SolarDoubleAltArrowRightBold: typeof import('~icons/solar/double-alt-arrow-right-bold')['default']
    SolarDoubleAltArrowRightBroken: typeof import('~icons/solar/double-alt-arrow-right-broken')['default']
    StatusIndicator: typeof import('./components/StatusIndicator.vue')['default']
  }
}
